config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sing_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
              reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :subtitle, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  skip_before_action :verify_authenticity_token
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
    #you could do @portfolio_items = Portfolio.includes(:author, :skill) if Portfolio was a JOIN table.
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
    # this above line is simply saying that this sort method doesn't need to render a new view.
  end

  def angular
      @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created, dawg.' }
        #format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        #format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update


    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        #format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        #format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    #perform the lookup for the record


    #destroy/delete the record
    @portfolio_item.destroy

    #redirect to portfolios_url
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was removed.' }
      #format.json { head :no_content }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(
      :title,
      :subtitle,
      :body,
      :main_image,
      :thumb_image,
      technologies_attributes: [:name]
    )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="btn btn-primary">
        Upload a main image <%= form.file_field :main_image, style: 'display:none;' %>
      </label>
    </div>
    <div class="form-group">
      <label class="btn btn-primary">
        Upload a thumb image <%= form.file_field :thumb_image, style: 'display:none;' %>
      </label>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control', rows: 12 %>
    </div>
  </div>
  <div class="col-md-12">
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name, class: 'form-control' %>
      <% end %>
    </div>

    <div class="actions">
      <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block'%>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb') %>
    <div class="card-body">
      <p class="card-text"><%= portfolio_item.title %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'View', portfolio_show_path(portfolio_item) if logged_in?(:site_admin) %></button>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Edit', edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %></button>
        </div>
        <!-- <small class="text-muted">9 mins</small> -->
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<h1>Angular Portfolio Items</h1>

<% @angular_portfolio_items.each do | portfolio_item | %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'YO YO YO, you fo real??? You SURE you want to delete this bad boy??' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>
      </div>
    </div>
  </div>
</main>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a New Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used</h3>
      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
      <%= link_to 'View all portfolio items', portfolios_path %>
      <%= link_to 'Edit', edit_portfolio_path %>
    </div>
  </div>
</div>